# Generated by Django 4.0 on 2022-12-03 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_language_book_lan_bookinstance_lan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='lan',
        ),
        migrations.RemoveField(
            model_name='book',
            name='lan',
        ),
        migrations.AddField(
            model_name='book',
            name='lan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.language'),
        ),
    ]
